version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: vehicle-scraper-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: olx_data
    ports:
      - "3308:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: vehicle-scraper-selenium
    ports:
      - "4444:4444"
    shm_size: '2gb'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle-scraper-app
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=olx_data
    depends_on:
      db:
        condition: service_healthy
      selenium:
        condition: service_started
    volumes:
      - ./app:/app/app
      - ./init:/app/init
      - ./debug:/app/debug

    command: ["python", "app/main.py"]
